language: python
services:
  - mongodb
python:
  - "3.6"
install:
  - pip install pyyaml pytest pytest-cov coveralls
  - pip install .
before_script:
  - sleep 5
script:
  - pytest --cov=mongoshapes
after_success:
  - coveralls